#!/bin/bash

function clean_dwm() {
    cd ..
    git submodule deinit -f .
    git submodule update --init --recursive
    cd -
    make clean && \
        rm -f config.h && \
        rm -f ./*.rej ./*.orig
}

function build_dwm() {
    for p in "$@"; do
      printf "patching: %s\n" "$p"
      patch -p1 < "$p" || exit 1
    make && \
        sudo make install && \
        rm -f ./*.rej ./*.orig
    read -n 1 -p Continue?
    make clean && \
        rm -f config.h && \
        rm -f ./*.rej ./*.orig
    done
}

cd dwm || exit

#generate config.def.h.old without custom patches
clean_dwm
patches=(../patches/dwm-*)
build_dwm "${patches[@]}"
cp config.def.h config.def.h.old && unset patches

#reset and patch with our changes
clean_dwm
patches=(../patches/dwm-*)
patches+=(../patches/dwm_*)
build_dwm "${patches[@]}"

#build
make && \
    sudo make install && \
    rm -f ./*.rej ./*.orig
