#!/bin/sh

git submodule deinit -f .
git submodule update --init --recursive

make clean && \
    rm config.h && \
    rm -f *.rej *.orig

cd dwm
patches=(../patches/dwm-*)
patches+=(../patches/dwm_*)

for p in "${patches[@]}"; do
  printf "patching: %s" $p
  patch -p1 < $p || exit 1
done

make && \
    sudo make install && \
    rm -f *.rej *.orig
