#!/bin/sh
cd dwm
make clean && rm config.h; git reset --hard origin/master
rm -f *.rej *.orig
for f in ../patches/dwm-*; do
  echo "patching: " $f
  patch -p1 < $f || exit 1
done
echo "patching dwm_git_config.diff"
patch -p1 < ../patches/dwm_git_config.diff || exit 1
make && sudo make install && rm -f *.rej *.orig
