name: build_test

on:
  push:
    branches:
      - master
      - testing

  workflow_dispatch:

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v2
      
      - name: Clone dwm
        run: git clone https://git.suckless.org/dwm /tmp/dwm_base && cp -a $GITHUB_WORKSPACE/* /tmp/dwm_base/

      - name: Test dwm patch and build
        working-directory: /tmp/dwm_base
        run: ./patch
